# -*- coding: utf-8 -*-
"""Agent Moons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185gjMNLfL4xKrFBDpYGxVOAJMvWraG0u
"""

import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import ipywidgets as widgets
from IPython.display import display, clear_output

# --- UI CONFIGURATION ---
style = {'description_width': 'initial'}
ticker_in = widgets.Text(value='META', description='🔍 Symbole:', style=style)
cap_in = widgets.FloatText(value=10000, description='💰 Capital ($):', style=style)
risk_in = widgets.FloatSlider(value=1.0, min=0.5, max=5.0, step=0.1, description='⚠️ Risque (%):', style=style)
btn_go = widgets.Button(description='Générer Plan de Trade', button_style='success', icon='calculator')
out = widgets.Output()

def tracer_complet(df, prix, stop, tp1, tp2, qte, capital, ticker):
    fig = make_subplots(rows=1, cols=2, column_widths=[0.7, 0.3], specs=[[{"type": "xy"}, {"type": "domain"}]])
    fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name='Prix'), row=1, col=1)
    fig.add_hline(y=stop, line_dash="dash", line_color="red", annotation_text="🛡️ STOP", row=1, col=1)
    fig.add_hline(y=tp1, line_dash="dot", line_color="cyan", annotation_text="🎯 TP1", row=1, col=1)
    fig.add_hline(y=tp2, line_dash="dot", line_color="gold", annotation_text="🚀 TP2", row=1, col=1)

    val_pos = qte * prix
    fig.add_trace(go.Pie(labels=['Position', 'Cash'], values=[val_pos, max(0, capital-val_pos)],
                         marker=dict(colors=['#4CAF50', '#333']), hole=.3), row=1, col=2)

    fig.update_layout(template="plotly_dark", height=400, margin=dict(l=10, r=10, t=50, b=10), showlegend=False)
    fig.show()

def analyse(b):
    with out:
        clear_output()
        try:
            tk = ticker_in.value.upper()
            c, r = cap_in.value, risk_in.value / 100

            df = yf.download(tk, period="30d", interval="1d", auto_adjust=True, progress=False)
            if df.empty: raise ValueError("Symbole non trouvé.")
            if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.get_level_values(0)

            w = df.tail(15)
            s, b_p = w['High'].max(), w['Low'].min()
            amp = s - b_p

            df_m = yf.download(tk, period="2d", interval="15m", auto_adjust=True, progress=False)
            if isinstance(df_m.columns, pd.MultiIndex): df_m.columns = df_m.columns.get_level_values(0)

            px = df_m['Close'].iloc[-1]
            sl = (df_m['High'].rolling(26).max() + df_m['Low'].rolling(26).min()).iloc[-1] / 2

            if px <= sl:
                display(widgets.HTML(f"<div style='border:2px solid #f44336;padding:15px;border-radius:10px;background-color:#1e1e1e;color:white;'>⚠️ ATTENTE : PRIX ({px:.2f}$) SOUS LA KIJUN ({sl:.2f}$)</div>"))
                return

            tp1, tp2 = s + (0.27 * amp), s + (0.618 * amp)
            q_tot = int((c * r) / (px - sl))
            v1, v2 = q_tot // 2, q_tot - (q_tot // 2)

            display(widgets.HTML(f"""
                <div style="border: 2px solid #4CAF50; padding: 15px; border-radius: 10px; background-color: #1e1e1e; color: white;">
                    <h3 style="margin:0; color: #4CAF50;">💎 ANALYSE VALIDÉE : {tk}</h3>
                    <div style="display: flex; justify-content: space-between; margin-top:10px;">
                        <div>
                            <b style="font-size:18px; color:#4CAF50;">🟢 ENTRÉE : {px:.2f} $</b><br>
                            <b style="color:#ff5252;">🛡️ STOP LOSS : {sl:.2f} $</b><br>
                            <b>💰 RISQUE : {(c*r):.2f} $ ({risk_in.value}%)</b>
                        </div>
                        <div style="text-align: right;">
                            <b style="font-size:18px;">📦 QTÉ TOTALE : {q_tot}</b><br>
                            <span style="color:#00e5ff;">🎯 TP1 (50%) : {tp1:.2f} $</span><br>
                            <span style="color:#ffeb3b;">🚀 TP2 (50%) : {tp2:.2f} $</span>
                        </div>
                    </div>
                </div>
            """))
            tracer_complet(df, px, sl, tp1, tp2, q_tot, c, tk)
        except Exception as e: print(f"❌ Erreur : {e}")

btn_go.on_click(analyse)
display(widgets.VBox([ticker_in, cap_in, risk_in, btn_go]))
display(out)